skills_values = {
    "min_age": '',
    "max_age": '',
    "min_value": '',
    "max_value": '',
    "min_price": '',
    "max_price": '',
    "nationality": '',
    "min_stamina": '',
    "max_stamina": '',
    "min_Keeper": '',
    "max_Keeper": '',
    "min_Pace": '',
    "max_Pace": '',
    "min_Defender": '',
    "max_Defender": '',
    "min_Technique": '',
    "max_Technique": '',
    "min_Playmaker": '',
    "max_Playmaker": '',
    "min_Passing": '',
    "max_Passing": '',
    "min_Striker":'',
    "max_Striker":'',
}